pool:
  name: Azure Pipelines
steps:
- task: Docker@0
  displayName: 'Build an image'
  inputs:
    azureSubscription: 'Visual Studio Enterprise Subscription (e2452abf-e102-49da-b222-bf041f8faad3)'
    azureContainerRegistry: '{"loginServer":"tpluscontainerregistry.azurecr.io", "id" : "/subscriptions/e2452abf-e102-49da-b222-bf041f8faad3/resourceGroups/tplus-RG/providers/Microsoft.ContainerRegistry/registries/tplusContainerRegistry"}'

- task: Docker@0
  displayName: 'Push an image'
  inputs:
    azureSubscription: 'Visual Studio Enterprise Subscription (e2452abf-e102-49da-b222-bf041f8faad3)'
    azureContainerRegistry: '{"loginServer":"tpluscontainerregistry.azurecr.io", "id" : "/subscriptions/e2452abf-e102-49da-b222-bf041f8faad3/resourceGroups/tplus-RG/providers/Microsoft.ContainerRegistry/registries/tplusContainerRegistry"}'
    action: 'Push an image'

- task: HelmInstaller@0
  displayName: 'Helm install'

- task: HelmDeploy@0
  displayName: 'helm package'
  inputs:
    azureSubscription: 'Visual Studio Enterprise Subscription (e2452abf-e102-49da-b222-bf041f8faad3)'
    azureResourceGroup: 'tplus-RG'
    kubernetesCluster: 'tplus-aks'
    command: package
    chartPath: 'helm-app'
    chartVersion: '$(Build.BuildId)'

- task: PublishPipelineArtifact@1
  displayName: 'Publish Pipeline Artifact'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'tplus-helm-artifact'
