trigger: none

pr: none

pool:
  name: Azure Pipelines
steps:

- task: Docker@0
  displayName: 'Build an image'
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Visual Studio Enterprise Subscription (e2452abf-e102-49da-b222-bf041f8faad3)'
    azureContainerRegistry: '{"loginServer":"tpluscontainerregistry.azurecr.io", "id" : "/subscriptions/e2452abf-e102-49da-b222-bf041f8faad3/resourceGroups/tplus-RG/providers/Microsoft.ContainerRegistry/registries/tplusContainerRegistry"}'
    action: 'Build an image'
    dockerFile: '**/Dockerfile'
    imageName: '$(Build.Repository.Name):$(Build.BuildId)'
    includeSourceTags: true
    includeLatestTag: true

- task: Docker@0
  displayName: 'Push an image'
  inputs:
    azureSubscription: 'Visual Studio Enterprise Subscription (e2452abf-e102-49da-b222-bf041f8faad3)'
    azureContainerRegistry: '{"loginServer":"tpluscontainerregistry.azurecr.io", "id" : "/subscriptions/e2452abf-e102-49da-b222-bf041f8faad3/resourceGroups/tplus-RG/providers/Microsoft.ContainerRegistry/registries/tplusContainerRegistry"}'
    action: 'Push an image'

- task: HelmInstaller@0
  displayName: 'Helm install'

- task: HelmDeploy@0
  displayName: 'helm package'
  inputs:
    azureSubscription: 'Visual Studio Enterprise Subscription (e2452abf-e102-49da-b222-bf041f8faad3)'
    azureResourceGroup: 'tplus-RG'
    kubernetesCluster: 'tplus-helm-aks'
    command: package
    chartPath: 'helm-app'
    chartVersion: '$(Build.BuildId)'

- task: PublishPipelineArtifact@1
  displayName: 'Publish Pipeline Artifact'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'tplus-helm-artifact'

- task: HelmDeploy@0
  displayName: 'helm upgrade'
  inputs:
    connectionType: Kubernetes Service Connection
    azureSubscription: 'Visual Studio Enterprise Subscription (e2452abf-e102-49da-b222-bf041f8faad3)'
    azureResourceGroup: 'tplus-RG'
    kubernetesCluster: 'tplus-helm-aks'
    command: upgrade
    chartType: FilePath
    chartPath: '$(System.DefaultWorkingDirectory)/_tplus-Docker container-CI/tplus-helm-artifact/nodeapi-*.tgz'
    chartVersion: '$(Build.BuildId)'
    releaseName: samplehelmapi
    waitForExecution: false